# Generated by Django 5.2.12 on 2026-09-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'permissions': [('close_branch', 'Filialni yopish'), ('open_branch', 'Filialni ochish')], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiallar'},
        ),
    ]
