# Generated by Django 5.2.12 on 2026-09-26 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organization",
            "0002_alter_branch_options_alter_organization_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                decimal_places=7,
                default=0,
                max_digits=10,
                verbose_name="Kenglik (Latitude)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                decimal_places=7,
                default=0,
                max_digits=10,
                verbose_name="Uzunlik (Longitude)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="radius",
            field=models.PositiveIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="Radius (metr)",
            ),
        ),
    ]
