# Generated by Django 5.2.12 on 2026-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_branch_latitude_branch_longitude_branch_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Kenglik (Latitude)",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Uzunlik (Longitude)",
            ),
        ),
    ]
