# Generated by Django 5.2.12 on 2026-09-24 08:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        (
            "organization",
            "0002_alter_branch_options_alter_organization_options_and_more",
        ),
        ("warehouse", "0002_carpetroll_productstock_stocktransaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="F.I.Sh.")),
                ("phone", models.CharField(max_length=50, verbose_name="Telefon")),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Manzil"),
                ),
                (
                    "balance_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Nasiya balansi",
                    ),
                ),
                (
                    "loyalty_discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Doimiy chegirma foizi",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mijoz",
                "verbose_name_plural": "Mijozlar",
                "db_table": "sales_customer",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Chegirmasiz jami summa",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Chegirma summasi",
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Yakuniy summa"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="To'langan summa",
                    ),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Nasiya summa",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "To'langan"),
                            ("partially_paid", "Qisman to'langan"),
                            ("debt", "Nasiya"),
                            ("unpaid", "To'lanmagan"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="To'lov holati",
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("completed", "Yakunlangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Chek holati",
                    ),
                ),
                (
                    "overlock_included",
                    models.BooleanField(
                        default=False, verbose_name="Tikish (ovirlok) xizmati bormi"
                    ),
                ),
                (
                    "delivery_required",
                    models.BooleanField(
                        default=False, verbose_name="Yetkazib berish kerakmi"
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True, default="", verbose_name="Yetkazib berish manzili"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yetkazib berish sanasi"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="organization.branch",
                        verbose_name="Filial",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pulni qabul qilgan xodim",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashier_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kassir",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bo'sh bo'lsa — nomsiz xaridor",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="sales.customer",
                        verbose_name="Mijoz",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sold_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sotgan xodim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sotuv cheki",
                "verbose_name_plural": "Sotuv cheklari",
                "db_table": "sales_order",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Sotilgan eni, metr",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Yo'lak bo'lsa kesib berilgan uzunlik",
                        max_digits=8,
                        verbose_name="Sotilgan bo'yi, metr",
                    ),
                ),
                (
                    "sqm",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Kvadrat metr"
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Sotilgan paytdagi 1 kv.m narxi",
                    ),
                ),
                (
                    "item_subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Qator summasi"
                    ),
                ),
                (
                    "overlock_length_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Tikilgan chet uzunligi, metr",
                    ),
                ),
                (
                    "overlock_price_per_meter",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Ovirlok, 1 metr narxi",
                    ),
                ),
                (
                    "overlock_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Jami ovirlok narxi",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name="Soni (tayyor o'lchamli dona gilamlar uchun)",
                    ),
                ),
                (
                    "final_item_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="(item_subtotal + overlock_cost) * quantity",
                        max_digits=15,
                        verbose_name="Yakuniy qator narxi",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.order",
                        verbose_name="Chek",
                    ),
                ),
                (
                    "product_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.productparty",
                        verbose_name="Mahsulot partiyasi",
                    ),
                ),
                (
                    "roll",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kesilgan yo'lak bo'lsa, qaysi jismoniy rulondan kesildi",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="warehouse.carpetroll",
                        verbose_name="Rulon",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Qaysi ombordan mahsulot kamaydi",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="warehouse.warehouse",
                        verbose_name="Ombor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chek qatori",
                "verbose_name_plural": "Chek qatorlari",
                "db_table": "sales_order_item",
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "phone"], name="sales_custo_organiz_f76d69_idx"
            ),
        ),
    ]
