# Generated by Django 5.2.12 on 2026-09-24 08:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0002_alter_branch_options_alter_organization_options_and_more",
        ),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Mijozga qaytarilgan summa",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="Sababi"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_orders",
                        to="organization.branch",
                        verbose_name="Filial",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_orders",
                        to="sales.customer",
                        verbose_name="Mijoz",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Qaysi sotuv cheki bo'yicha qaytarildi",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_orders",
                        to="sales.order",
                        verbose_name="Sotuv cheki",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_orders",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qaytarish hujjati",
                "verbose_name_plural": "Qaytarish hujjatlari",
                "db_table": "sales_return_order",
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Soni (dona gilamlar uchun)"
                    ),
                ),
                (
                    "length_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Qaytarilgan uzunligi, metr (yo'laklar uchun)",
                    ),
                ),
                (
                    "restock_status",
                    models.CharField(
                        choices=[
                            ("restocked", "Omborga qaytarildi"),
                            ("damaged_scrap", "Brak (hisobdan o'chirildi)"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="sales.orderitem",
                        verbose_name="Sotilgan chek qatori",
                    ),
                ),
                (
                    "return_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.returnorder",
                        verbose_name="Qaytarish hujjati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qaytarish qatori",
                "verbose_name_plural": "Qaytarish qatorlari",
                "db_table": "sales_return_item",
            },
        ),
    ]
