# Generated by Django 5.2.12 on 2026-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_remove_installmentagreement_customer_and_more"),
        ("sales", "0002_returnorder_returnitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="returnorder",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cashier",
        ),
        migrations.RemoveField(
            model_name="order",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="returnorder",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_party",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="roll",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="returnitem",
            name="order_item",
        ),
        migrations.RemoveField(
            model_name="returnitem",
            name="return_order",
        ),
        migrations.RemoveField(
            model_name="returnorder",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="returnorder",
            name="organization",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="ReturnItem",
        ),
        migrations.DeleteModel(
            name="ReturnOrder",
        ),
    ]
