# Generated by Django 5.2.12 on 2026-09-17 13:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_user_branch_remove_user_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("block_user", "Foydalanuvchini bloklash"),
                    ("unblock_user", "Foydalanuvchini blokdan chiqarish"),
                ],
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
            },
        ),
        migrations.CreateModel(
            name="UserBlockLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("block", "Bloklash"),
                            ("unblock", "Blokdan chiqarish"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="Sababi"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_block_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bajaruvchi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloklash yozuvi",
                "verbose_name_plural": "Bloklash yozuvlari",
                "db_table": "accounts_user_block_log",
            },
        ),
    ]
