# Generated by Django 5.2.12 on 2026-09-24 08:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        (
            "organization",
            "0002_alter_branch_options_alter_organization_options_and_more",
        ),
        ("warehouse", "0002_carpetroll_productstock_stocktransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Telefon"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Manzil"),
                ),
                (
                    "balance_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Bizning yetkazuvchidan qarzimiz",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yetkazuvchi",
                "verbose_name_plural": "Yetkazuvchilar",
                "db_table": "procurement_supplier",
            },
        ),
        migrations.CreateModel(
            name="SupplierPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Jami summa"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="To'langan summa",
                    ),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Qarz summa",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_purchases",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="procurement.supplier",
                        verbose_name="Yetkazuvchi",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_purchases",
                        to="warehouse.warehouse",
                        verbose_name="Ombor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xarid hujjati",
                "verbose_name_plural": "Xarid hujjatlari",
                "db_table": "procurement_supplier_purchase",
            },
        ),
        migrations.CreateModel(
            name="SupplierPurchaseItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Kirim qilingan yo'lak (runner) bo'lsa, rulonning unikal raqami",
                        max_length=100,
                        verbose_name="Rulon raqami",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Eni, metr"
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Yo'lak (runner) uchun bo'sh bo'lishi mumkin (faqat eni kelganda)",
                        max_digits=8,
                        null=True,
                        verbose_name="Bo'yi, metr",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Soni (dona gilam uchun)"
                    ),
                ),
                (
                    "total_length_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Rulon uzunligi, metr (yo'lak uchun)",
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Sotib olingan narx, 1 kv.m",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Qator summasi"
                    ),
                ),
                (
                    "product_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_purchase_items",
                        to="catalog.productparty",
                        verbose_name="Mahsulot partiyasi",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.supplierpurchase",
                        verbose_name="Xarid hujjati",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xarid qatori",
                "verbose_name_plural": "Xarid qatorlari",
                "db_table": "procurement_supplier_purchase_item",
            },
        ),
    ]
