# Generated by Django 5.2.12 on 2026-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0002_supplierpurchase_document_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierpurchase",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="supplierpurchase",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="supplierpurchase",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="supplierpurchase",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="supplierpurchaseitem",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="supplierpurchaseitem",
            name="product_party",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
        migrations.DeleteModel(
            name="SupplierPurchase",
        ),
        migrations.DeleteModel(
            name="SupplierPurchaseItem",
        ),
    ]
