# Generated by Django 5.2.12 on 2026-09-24 08:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
        (
            "organization",
            "0002_alter_branch_options_alter_organization_options_and_more",
        ),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "total_debt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Jami qarz summasi",
                    ),
                ),
                (
                    "remaining_debt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Qolgan qarz summasi",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="To'lash oxirgi muddati"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("paid", "To'langan"),
                            ("overdue", "Muddati o'tgan"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_ledgers",
                        to="sales.customer",
                        verbose_name="Mijoz",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_ledgers",
                        to="sales.order",
                        verbose_name="Sotuv cheki",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debt_ledgers",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nasiya daftari",
                "verbose_name_plural": "Nasiya daftarlari",
                "db_table": "finance_debt_ledger",
            },
        ),
        migrations.CreateModel(
            name="InstallmentAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "agreement_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Shartnoma raqami"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Jami summa (ustamalari bilan)",
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Boshlang'ich to'lov",
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Qolgan muddatli to'lanadigan summa",
                    ),
                ),
                (
                    "number_of_months",
                    models.PositiveIntegerField(verbose_name="Necha oyga bo'lingan"),
                ),
                (
                    "markup_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Ustama foizi (rassrochka ustamasi)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("closed", "Tugatilgan"),
                            ("overdue", "Kechikayotgan"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_agreements",
                        to="sales.customer",
                        verbose_name="Mijoz",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_agreement",
                        to="sales.order",
                        verbose_name="Sotuv cheki",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_agreements",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muddatli to'lov shartnomasi",
                "verbose_name_plural": "Muddatli to'lov shartnomalari",
                "db_table": "finance_installment_agreement",
            },
        ),
        migrations.CreateModel(
            name="InstallmentSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "payment_number",
                    models.PositiveIntegerField(verbose_name="Nechinchi oylik to'lov"),
                ),
                ("due_date", models.DateField(verbose_name="To'lov muddati")),
                (
                    "amount_to_pay",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="To'lanishi kerak bo'lgan oylik qism",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Haqiqatda to'langan qism",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("paid", "To'langan"),
                            ("partially_paid", "Qisman to'langan"),
                            ("overdue", "Kechikkan"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="finance.installmentagreement",
                        verbose_name="Shartnoma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oylik to'lov grafigi",
                "verbose_name_plural": "Oylik to'lov grafiklari",
                "db_table": "finance_installment_schedule",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Summa"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Terminal"),
                            ("bank_transfer", "Bank o'tkazmasi"),
                            ("click", "Click"),
                            ("payme", "Payme"),
                            ("apelsin", "Apelsin"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="To'lov usuli",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("order_payment", "Sotuv to'lovi"),
                            ("debt_payment", "Nasiya to'lovi"),
                            ("down_payment", "Boshlang'ich muddatli to'lov"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="To'lov turi",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nasiya yopilganda kim to'laganini bilish uchun",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.customer",
                        verbose_name="Mijoz",
                    ),
                ),
                (
                    "installment_agreement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shartnoma bo'yicha to'lov bo'lsa bog'lanadi",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.installmentagreement",
                        verbose_name="Muddatli to'lov shartnomasi",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sotuv to'lovi bo'lsa bog'lanadi",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.order",
                        verbose_name="Sotuv cheki",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
                "db_table": "finance_payment",
            },
        ),
    ]
