# Generated by Django 5.2.12 on 2026-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0002_debtledger_installmentagreement_installmentschedule_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="installmentagreement",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="installmentagreement",
            name="order",
        ),
        migrations.RemoveField(
            model_name="installmentagreement",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="installment_agreement",
        ),
        migrations.RemoveField(
            model_name="installmentschedule",
            name="agreement",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="organization",
        ),
        migrations.DeleteModel(
            name="DebtLedger",
        ),
        migrations.DeleteModel(
            name="InstallmentAgreement",
        ),
        migrations.DeleteModel(
            name="InstallmentSchedule",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
