# Generated by Django 5.2.12 on 2026-09-26 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_installmentagreement_customer_and_more'),
        ('hr', '0010_employeetimesheet_employeetimesheetitem'),
        ('organization', '0002_alter_branch_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualretention',
            name='is_retention',
            field=models.BooleanField(db_index=True, default=False, help_text="True — ushlab qolish (ayiriladi), False — hisoblash (qo'shiladi).", verbose_name='Ushlab qolishmi'),
        ),
        migrations.CreateModel(
            name='AccrualRetentionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Sana')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('approved', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='draft', max_length=20, verbose_name='Holati')),
                ('accrual_retention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='finance.accrualretention', verbose_name='Hisoblash / ushlab qolish')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrual_retention_documents', to='organization.branch', verbose_name='Filial')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrual_retention_documents', to='hr.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Hisoblash / ushlab qolish hujjati',
                'verbose_name_plural': 'Hisoblash / ushlab qolish hujjatlari',
                'db_table': 'finance_accrual_retention_document',
            },
        ),
    ]
