"""Markaziy bank valyutalari (tanlash uchun tayyor ro'yxat, bazaga saqlanmaydi)."""

# (kod, nomi uz, nomi en, nomi ru) — bank ro'yxatida so'm yo'q, shuning uchun UZS qo'lda qo'shilgan
BANK_CURRENCIES = [
    ("UZS", "O'zbekiston so'mi", "Uzbekistan Sum", "Узбекский сум"),
    ("AED", "BAA dirhami", "UAE Dirham", "Дирхам ОАЭ"),
    ("AFN", "Afg‘oniston afg‘onisi", "AF Afghani", "Афгани"),
    ("AMD", "Armaniston drami", "Armenian Dram", "Армянский драм"),
    ("ARS", "Argentina pesosi", "Argentine Peso", "Аргентинское песо"),
    ("AUD", "Avstraliya dollari", "Australian Dollar", "Австралийский доллар"),
    ("AZN", "Ozarbayjon manati", "Azerbaijan Manat", "Азербайджанский манат"),
    ("BDT", "Bangladesh takasi", "Bangladesh Taka", "Бангладешская така"),
    ("BHD", "Bahrayn dinori", "Bahraini Dinar", "Бахрейнский динар"),
    ("BND", "Bruney dollari", "Brunei Dollar", "Брунейский доллар"),
    ("BRL", "Braziliya reali", "Brazilian Real", "Бразильский реал"),
    ("BYN", "Belorus rubli", "Belarusian Ruble", "Белорусский рубль"),
    ("CAD", "Kanada dollari", "Canadian Dollar", "Канадский доллар"),
    ("CHF", "Shveytsariya franki", "Swiss Franc", "Швейцарский франк"),
    ("CNY", "Xitoy yuani", "Yuan Renminbi", "Юань ренминби"),
    ("CUP", "Kuba pesosi", "Cuban Peso", "Кубинское песо"),
    ("CZK", "Chexiya kronasi", "Czech Koruna", "Чешская крона"),
    ("DKK", "Daniya kronasi", "Danish Krone", "Датская крона"),
    ("DZD", "Jazoir dinori", "Algerian Dinar", "Алжирский динар"),
    ("EGP", "Misr funti", "Egyptian Pound", "Египетский фунт"),
    ("EUR", "EVRO", "Euro", "Евро"),
    ("GBP", "Angliya funt sterlingi", "Pound Sterling", "Фунт стерлингов"),
    ("GEL", "Gruziya larisi", "Georgian Lari", "Грузинский лари"),
    ("HKD", "Gongkong dollari", "Hong Kong Dollar", "Гонгконгский доллар"),
    ("HUF", "Vengriya forinti", "Hungarian Forint", "Венгерский форинт"),
    ("IDR", "Indoneziya rupiyasi", "Rupiah", "Рупия"),
    ("ILS", "Isroil shekeli", "New Israeli Sheqel", "Новый израильский шекель"),
    ("INR", "Hindiston rupiyasi", "Indian Rupee", "Индийская рупия"),
    ("IQD", "Iroq dinori", "Iraqi Dinar", "Иракский динар"),
    ("IRR", "Eron riali", "Iranian Rial", "Иранский риал"),
    ("ISK", "Islandiya kronasi", "Iceland Krona", "Исландская крона"),
    ("JOD", "Iordaniya dinori", "Jordanian Dinar", "Иорданский динар"),
    ("JPY", "Yaponiya iyenasi", "Japan Yen", "Иена"),
    ("KGS", "Qirg‘iz somi", "Kyrgyzstan Som", "Киргизский сом"),
    ("KHR", "Kambodja riyeli", "Riel", "Риель"),
    (
        "KRW",
        "Koreya Respublikasi voni",
        "The Korean Republic Won",
        "Вона Республики Корея",
    ),
    ("KWD", "Quvayt dinori", "Kuwaiti Dinar", "Кувейтский динар"),
    ("KZT", "Qozog‘iston tengesi", "Kazakhstan Tenge", "Казахстанский тенге"),
    ("LAK", "Laos kipisi", "Lao Kip", "Лаосский кип"),
    ("LBP", "Livan funti", "Lebanese Pound", "Ливанский фунт"),
    ("LYD", "Liviya dinori", "Libyan Dinar", "Ливийский динар"),
    ("MAD", "Marokash dirhami", "Moroccan Dirham", "Марокканский дирхам"),
    ("MDL", "Moldaviya leyi", "Moldovan Leu", "Молдавский лей"),
    ("MMK", "Myanma kyati", "Kyat", "Мьянманский кьят"),
    ("MNT", "Mongoliya tugriki", "Tugrik", "Монгольский тугpик"),
    ("MXN", "Meksika pesosi", "Mexican Peso", "Мексиканское песо"),
    ("MYR", "Malayziya ringgiti", "Malaysian Ringgit", "Малайзийский ринггит"),
    ("NOK", "Norvegiya kronasi", "Norwegian Krone", "Норвежская крона"),
    ("NZD", "Yangi Zelandiya dollari", "New Zealand Dollar", "Новозеландский доллар"),
    ("OMR", "Ummon riali", "Rial Omani", "Оманский риал"),
    ("PHP", "Filippin pesosi", "Philippine Piso", "Филиппинское песо"),
    ("PKR", "Pokiston rupiyasi", "Pakistan Rupee", "Пакистанская рупия"),
    ("PLN", "Polsha zlotiysi", "Polish Zloty", "Злотый"),
    ("QAR", "Qatar riali", "Qatari Rial", "Катарский риал"),
    ("RON", "Ruminiya leyi", "Romanian Leu", "Румынский лей"),
    ("RSD", "Serbiya dinori", "Serbian Dinar", "Сербский динар"),
    ("RUB", "Rossiya rubli", "Russian Ruble", "Российский рубль"),
    ("SAR", "Saudiya Arabistoni riali", "Saudi Riyal", "Саудовский риял"),
    ("SDG", "Sudan funti", "Sudanese Pound", "Суданский фунт"),
    ("SEK", "Shvetsiya kronasi", "Swedish Krona", "Шведская крона"),
    ("SGD", "Singapur dollari", "Singapore Dollar", "Сингапурский доллар"),
    ("SYP", "Suriya funti", "Syrian Pound", "Сирийский фунт"),
    ("THB", "Tailand bati", "Baht", "Бат"),
    ("TJS", "Tojikiston somonisi", "Tajikistan Somoni", "Сомони"),
    ("TMT", "Turkmaniston manati", "Turkmenistan New Manat", "Новый туркменский манат"),
    ("TND", "Tunis dinori", "Tunisian Dinar", "Тунисский динар"),
    ("TRY", "Turkiya lirasi", "Turkish Lira", "Турецкая лира"),
    ("UAH", "Ukraina grivnasi", "Ukrainian Hryvnia", "Гривна"),
    ("USD", "AQSH dollari", "US Dollar", "Доллар США"),
    ("UYU", "Urugvay pesosi", "Peso Uruguayo", "Уругвайское песо"),
    ("VES", "Venesuela bolivari", "Bolívar", "Венесуэльский боливар"),
    ("VND", "Vetnam dongi", "Dong", "Донг"),
    ("XDR", "SDR", "SDR", "СДР"),
    ("YER", "Yaman riali", "Yemeni Rial", "Йеменский риал"),
    ("ZAR", "Janubiy Afrika randi", "Rand", "Рэнд"),
]

CURRENCY_NAMES = {code: name_uz for code, name_uz, _, _ in BANK_CURRENCIES}
