# Generated by Django 5.2.12 on 2026-09-24 07:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        (
            "organization",
            "0002_alter_branch_options_alter_organization_options_and_more",
        ),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarpetRoll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Rulon raqami"
                    ),
                ),
                (
                    "initial_length_meters",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Boshlang'ich uzunligi (metr)",
                    ),
                ),
                (
                    "current_length_meters",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Hozirgi qolgan uzunligi (metr)",
                    ),
                ),
                (
                    "is_offcut",
                    models.BooleanField(
                        default=False,
                        verbose_name="Qiyqim (katta rulondan kesilgan qoldiq)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("sold_out", "Tugagan"),
                            ("damaged", "Brak"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "product_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carpet_rolls",
                        to="catalog.productparty",
                        verbose_name="Mahsulot partiyasi",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carpet_rolls",
                        to="warehouse.warehouse",
                        verbose_name="Ombor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rulon",
                "verbose_name_plural": "Rulonlar",
                "db_table": "warehouse_carpet_roll",
            },
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Soni (dona gilamlar uchun)"
                    ),
                ),
                (
                    "total_length_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Jami uzunligi, metr (yo'laklar uchun)",
                    ),
                ),
                (
                    "product_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_stocks",
                        to="catalog.productparty",
                        verbose_name="Mahsulot partiyasi",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_stocks",
                        to="warehouse.warehouse",
                        verbose_name="Ombor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ombor qoldig'i",
                "verbose_name_plural": "Ombor qoldiqlari",
                "db_table": "warehouse_product_stock",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "Kirim"),
                            ("out", "Chiqim"),
                            ("transfer", "Ko'chirish"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Harakat turi",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0, verbose_name="Soni (dona gilamlar uchun)"
                    ),
                ),
                (
                    "length_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Uzunligi, metr (yo'laklar uchun)",
                    ),
                ),
                (
                    "ref_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sale", "Sotuv"),
                            ("return", "Qaytarish"),
                            ("purchase", "Xarid (kirim)"),
                            ("adjustment", "Korrektirovka"),
                            ("transfer", "Ko'chirish"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Bog'liq hujjat turi",
                    ),
                ),
                (
                    "ref_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Masalan: Order.id, SupplierPurchase.id yoki ReturnOrder.id",
                        null=True,
                        verbose_name="Bog'liq hujjat id'si",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kirim bo'lsa bo'sh",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions_from",
                        to="warehouse.warehouse",
                        verbose_name="Qaysi ombordan",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="organization.organization",
                        verbose_name="Tashkilot",
                    ),
                ),
                (
                    "product_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="catalog.productparty",
                        verbose_name="Mahsulot partiyasi",
                    ),
                ),
                (
                    "roll",
                    models.ForeignKey(
                        blank=True,
                        help_text="Yo'lak (runner) bo'lsa, qaysi rulonda o'zgarish bo'ldi",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="warehouse.carpetroll",
                        verbose_name="Rulon",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chiqim bo'lsa bo'sh",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions_to",
                        to="warehouse.warehouse",
                        verbose_name="Qaysi omborga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ombor harakati",
                "verbose_name_plural": "Ombor harakatlari",
                "db_table": "warehouse_stock_transaction",
            },
        ),
        migrations.AddIndex(
            model_name="carpetroll",
            index=models.Index(
                fields=["warehouse", "product_party"],
                name="warehouse_c_warehou_30c585_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "product_party"),
                name="unique_warehouse_product_party_stock",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["ref_type", "ref_id"], name="warehouse_s_ref_typ_063bd5_idx"
            ),
        ),
    ]
