# Generated by Django 5.2.12 on 2026-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_remove_order_customer_remove_returnorder_customer_and_more"),
        ("warehouse", "0002_carpetroll_productstock_stocktransaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="roll",
        ),
        migrations.RemoveField(
            model_name="productstock",
            name="product_party",
        ),
        migrations.RemoveField(
            model_name="productstock",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="from_warehouse",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="product_party",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="to_warehouse",
        ),
        migrations.DeleteModel(
            name="CarpetRoll",
        ),
        migrations.DeleteModel(
            name="ProductStock",
        ),
        migrations.DeleteModel(
            name="StockTransaction",
        ),
    ]
