# Generated by Django 5.2.12 on 2026-09-17 13:25

import django.core.validators
from django.db import migrations, models

import apps.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_employee_organization_alter_employee_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentdismissal",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Ishga olish/bo'shatish uchun asos bo'lgan hujjat (PDF yoki Excel, 10 MB gacha)",
                null=True,
                upload_to="hr/recruitment_dismissals/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "xls", "xlsx"]
                    ),
                    apps.utils.validators.FileSizeValidator(max_size_mb=10),
                ],
                verbose_name="Asos hujjat",
            ),
        ),
    ]
