# Generated by Django 5.2.12 on 2026-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_recruitmentdismissal_attachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workschedule",
            options={
                "verbose_name": "Ish grafigi",
                "verbose_name_plural": "Ish grafiklari",
            },
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="from_date",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="to_date",
        ),
        migrations.AddField(
            model_name="workschedule",
            name="is_friday",
            field=models.BooleanField(default=False, verbose_name="Juma"),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="is_monday",
            field=models.BooleanField(default=False, verbose_name="Dushanba"),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="is_saturday",
            field=models.BooleanField(default=False, verbose_name="Shanba"),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="is_sunday",
            field=models.BooleanField(default=False, verbose_name="Yakshanba"),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="is_thursday",
            field=models.BooleanField(default=False, verbose_name="Payshanba"),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="is_tuesday",
            field=models.BooleanField(default=False, verbose_name="Seshanba"),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="is_wednesday",
            field=models.BooleanField(default=False, verbose_name="Chorshanba"),
        ),
        migrations.DeleteModel(
            name="WorkScheduleItem",
        ),
    ]
