# Generated by Django 5.2.12 on 2026-09-22 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0004_alter_workschedule_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workschedule",
            name="is_friday",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="is_monday",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="is_saturday",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="is_sunday",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="is_thursday",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="is_tuesday",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="is_wednesday",
        ),
        migrations.AddField(
            model_name="workschedule",
            name="days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (0, "Dushanba"),
                        (1, "Seshanba"),
                        (2, "Chorshanba"),
                        (3, "Payshanba"),
                        (4, "Juma"),
                        (5, "Shanba"),
                        (6, "Yakshanba"),
                    ]
                ),
                blank=True,
                default=list,
                help_text="Ish kunlari ro'yxati: 0=Dushanba, 1=Seshanba, 2=Chorshanba, "
                "3=Payshanba, 4=Juma, 5=Shanba, 6=Yakshanba. Masalan: [0, 1, 2, 3, 4]",
                size=None,
                verbose_name="Hafta kunlari",
            ),
        ),
    ]
