# Generated by Django 5.2.12 on 2026-09-25 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


def fill_default_work_days(apps, schema_editor):
    """Mavjud ish grafiklariga standart ish kunlarini (dushanba–shanba) qo'yadi."""
    apps.get_model("hr", "WorkSchedule").objects.update(work_days=[0, 1, 2, 3, 4, 5])


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_workschedule_branch_dates_workscheduleitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="workschedule",
            name="work_days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=list,
                help_text="0 — dushanba, 6 — yakshanba",
                size=None,
                verbose_name="Ish kunlari",
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="from_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Boshlanish sanasi"
            ),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="to_date",
            field=models.DateField(blank=True, null=True, verbose_name="Tugash sanasi"),
        ),
        migrations.RunPython(fill_default_work_days, migrations.RunPython.noop),
    ]
