# Generated by Django 5.2.12 on 2026-09-26 10:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0009_recruitmentdismissal_status"),
        (
            "organization",
            "0002_alter_branch_options_alter_organization_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTimesheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "for_month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Yanvar"),
                            (2, "Fevral"),
                            (3, "Mart"),
                            (4, "Aprel"),
                            (5, "May"),
                            (6, "Iyun"),
                            (7, "Iyul"),
                            (8, "Avgust"),
                            (9, "Sentabr"),
                            (10, "Oktabr"),
                            (11, "Noyabr"),
                            (12, "Dekabr"),
                        ],
                        db_index=True,
                        verbose_name="Oy",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("approved", "Tasdiqlangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_timesheets",
                        to="organization.branch",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xodimlar tabeli",
                "verbose_name_plural": "Xodimlar tabellari",
                "db_table": "hr_employee_timesheet",
            },
        ),
        migrations.CreateModel(
            name="EmployeeTimesheetItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Sana")),
                (
                    "work_hour_in_plan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Rejadagi ish soati",
                    ),
                ),
                (
                    "input_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kelgan vaqti"
                    ),
                ),
                (
                    "output_lunch_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tushlikka chiqqan vaqti"
                    ),
                ),
                (
                    "input_lunch_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tushlikdan kelgan vaqti"
                    ),
                ),
                (
                    "output_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ketgan vaqti"
                    ),
                ),
                (
                    "work_hour_in_fact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Haqiqiy ish soati",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timesheet_items",
                        to="hr.employee",
                        verbose_name="Xodim",
                    ),
                ),
                (
                    "employee_timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hr.employeetimesheet",
                        verbose_name="Tabel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabel qatori",
                "verbose_name_plural": "Tabel qatorlari",
                "db_table": "hr_employee_timesheet_item",
            },
        ),
    ]
