# Generated by Django 5.2.12 on 2026-09-26 11:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_accrualretention_is_retention_and_more'),
        ('hr', '0010_employeetimesheet_employeetimesheetitem'),
        ('organization', '0002_alter_branch_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeledger',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.CreateModel(
            name='CalculatingSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('for_month', models.PositiveSmallIntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], db_index=True, verbose_name='Oy')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Summa (UZS)')),
                ('currency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valyutadagi summa')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('approved', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='draft', max_length=20, verbose_name='Holati')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculating_salaries', to='organization.branch', verbose_name='Filial')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculating_salaries', to='finance.currency', verbose_name='Valyuta')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculating_salaries', to='hr.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Oylik hisobi',
                'verbose_name_plural': 'Oylik hisoblari',
                'db_table': 'hr_calculating_salary',
            },
        ),
    ]
