# Generated by Django 5.2.12 on 2026-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designphoto",
            name="design",
        ),
    ]
